services:
  webportfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webportofolio
    restart: unless-stopped
    networks:
      - caddy_net
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    expose:
      - "3000"

networks:
  caddy_net:
    external: true